= https://github.com/The-Blockchain-Company/zerepoch[The Zerepoch Platform and Simeon]
:email: zerepoch@bcccoin.io
:author: Input Output HK Limited
:toc: left
:reproducible:

The Zerepoch Platform is an application development platform for developing distributed applications using the Bcc blockchain; and Simeon is a platform specifically for financial products, built on top of Zerepoch.
For more information about the projects, see the <<user-documentation>>.

This repository contains:

* Zerepoch Platform
** The implementation, specification, and mechanized metatheory of Zerepoch Core, the scripting language embedded in the Bcc ledger.
** Zerepoch Tx, the compiler from Haskell to Zerepoch Core.
** Libraries which implement the Zerepoch Application Framework, a framework for writing applications that work with Bcc.
** A selection of end-to-end usecases written with the Zerepoch Application Framework
** The Zerepoch Playground, a web-based playground for learning and writing basic Zerepoch Applications.
* Simeon
** The implementation of the Simeon domain-specific language.
** Tools for working with Simeon, including static analysis.
** A selection of examples using Simeon, including a number based on the ACTUS financial standard.
** The Simeon Playground, a web-based playground for learning and writing Simeon Applications.

[IMPORTANT]
====
The rest of this README is focussed on people who want to develop or contribute to the Platform.

For people who want to *use* the Platform, please consult the <<user-documentation>>.
====

[[cache-warning]]
[IMPORTANT]
====
DO NOT IGNORE THIS

If you want to use Nix with this project, make sure to set up the xref:bcccoin-binary-cache[The Blockchain Co. binary cache].
If you do not do this, you will end up building GHC, which takes several hours.
If you find yourself building GHC, STOP and fix the cache.
====

== Documentation

=== User documentation

The main documentation is located https://zerepoch.readthedocs.io/en/latest/[here].

=== Talks

- https://www.youtube.com/watch?v=MpWeg6Fg0t8[Functional Smart Contracts on Bcc]
- https://www.youtube.com/watch?v=usMPt8KpBeI[The Zerepoch Platform]

=== Specifications and design

- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.zerepoch-report/latest/download-by-type/doc-pdf/zerepoch[Zerepoch Technical Report] (draft)
- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.zerepoch-core-spec/latest/download-by-type/doc-pdf/zerepoch-core-specification[Zerepoch Core Specification]
- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.extended-utxo-spec/latest/download-by-type/doc-pdf/extended-utxo-specification[Extended UTXO Model]

=== Academic papers

- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.papers.unraveling-recursion/latest/download-by-type/doc-pdf/unraveling-recursion[Unraveling Recursion] (https://doi.org/10.1007/978-3-030-33636-3_15[published version])
- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.papers.system-f-in-agda/latest/download-by-type/doc-pdf/paper[System F in Agda] (https://doi.org/10.1007/978-3-030-33636-3_10[published version])
- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.papers.eutxo/latest/download-by-type/doc-pdf/eutxo[The Extended UTXO Model] (in press)
- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.papers.utxoma/latest/download-by-type/doc-pdf/utxoma[UTXOma: UTXO with Multi-Asset Support] (in press)
- https://hydra.bcccoin.io/job/Bcc/zerepoch/linux.docs.papers.eutxoma/latest/download-by-type/doc-pdf/eutxoma[Native Custom Tokens in the Extended UTXO Model] (in press)

== Working with the project

=== How to submit an issue

Issues can be filed in the https://github.com/The-Blockchain-Company/zerepoch/issues[GitHub Issue tracker].

However, note that this is pre-release software, so we will not usually be providing support.

[[how-to-develop]]
=== How to develop and contribute to the project

See link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING], which describes our processes in more detail including development environments; and link:ARCHITECTURE{outfilesuffix}[ARCHITECTURE], which describes the structure of the repository.

=== How to depend on the project from another Haskell project

None of our libraries are on Hackage, unfortunately (many of our dependencies aren't either).
So for the time being, you need to:

. Add `zerepoch` as a `source-repository-package` to your `cabal.project`.
. Copy the `source-repository-package` stanzas from our `cabal.project` to yours.
. Copy additional stanzas from our `cabal.project` as you need, e.g. you may need some of the `allow-newer` stanzas.

The https://github.com/The-Blockchain-Company/zerepoch-starter[zerepoch-starter] project provides an example.

=== How to build the project's artifacts

This section contains information about how to build the project's artifacts for independent usage.
For development work see <<how-to-develop>> for more information.

[[prerequisites]]
==== Prerequisites

The Haskell libraries in the Zerepoch Platform are built with `cabal` and Nix.
The other artifacts (docs etc.) are also most easily built with Nix.

===== Nix

Install https://nixos.org/nix/[Nix] (recommended). following the instructions on the https://nixos.org/nix/[Nix website].

Make sure you have read and understood the xref:cache-warning[cache warning].
DO NOT IGNORE THIS.

See <<nix-advice>> for further advice on using Nix.

===== Non-Nix

You can build some of the Haskell packages without Nix, but this is not recommended and we don't guarantee that these prerequisites are sufficient.
If you use Nix, these tools are provided for you via `shell.nix`, and you do *not* need to install them yourself.

* If you want to build our Haskell packages with https://www.haskell.org/cabal/[`cabal`], then install it.
* If you want to build our Haskell packages with https://haskellstack.org/[`stack`], then install it.
* If you want to build our Agda code, then install https://github.com/agda/agda[Agda] and the https://github.com/agda/agda-stdlib[standard library].

[[building-with-nix]]
==== How to build the Haskell packages and other artifacts with Nix

Run `nix build -f default.nix zerepoch.haskell.packages.zerepoch-core.components.library` from the root to build the Zerepoch Core library.

See <<nix-build-attributes>> to find out what other attributes you can build.

==== How to build the Haskell packages with `cabal`

The Haskell packages can be built directly with `cabal`.
We do this during development (see <<how-to-develop>>).
The best way is to do this is inside a `nix-shell`.

[NOTE]
====
For fresh development setups, you also need to run `cabal update`.
====

Run `cabal build zerepoch-core` from the root to build the Zerepoch Core library.

See the link:./cabal.project[cabal project file] to see the other packages that you can build with `cabal`.


[[nix-advice]]
== Nix

[[bcccoin-binary-cache]]
=== How to set up the The Blockchain Co. binary caches

Adding the The Blockchain Co. binary cache to your Nix configuration will speed up
builds a lot, since many things will have been built already by our CI.

If you find you are building packages that are not defined in this
repository, or if the build seems to take a very long time then you may
not have this set up properly.

To set up the cache:

. On non-NixOS, edit `/etc/nix/nix.conf` and add the following lines:
+
----
substituters        = https://hydra.bcccoin.io https://bcccoin.cachix.org https://cache.nixos.org/
trusted-public-keys = hydra.bcccoin.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= bcccoin.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
----
+
[NOTE]
====
If you don't have an `/etc/nix/nix.conf` or don't want to edit it, you may add the `nix.conf` lines to `~/.config/nix/nix.conf` instead.
You must be a https://nixos.org/nix/manual/#ssec-multi-user[trusted user] to do this.
====
. On NixOS, set the following NixOS options:
+
----
nix = {
  binaryCaches          = [ "https://hydra.bcccoin.io" "https://bcccoin.cachix.org" ];
  binaryCachePublicKeys = [ "hydra.bcccoin.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" "bcccoin.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo=" ];
};
----


=== Nix on macOS

Nix on macOS can be a bit tricky. In particular, sandboxing is disabled by default, which can lead to strange failures.

These days it should be safe to turn on sandboxing on macOS with a few exceptions. Consider setting the following Nix settings, in the same way as in xref:bcccoin-binary-cache[previous section]:

----
sandbox = true
extra-sandbox-paths = /System/Library/Frameworks /System/Library/PrivateFrameworks /usr/lib /private/tmp /private/var/tmp /usr/bin/env
----


[[nix-build-attributes]]
=== Which attributes to use to build different artifacts

link:./default.nix[`default.nix`] defines a package set with attributes for all the artifacts you can build from this repository.
These can be built using `nix build`.
For example:

----
nix build -f default.nix docs.papers.eutxo
----

.Example attributes
* Project packages: defined inside `zerepoch.haskell.packages`
** e.g. `zerepoch.haskell.packages.zerepoch-core.components.library`
* Documents: defined inside `docs`
** e.g. `docs.zerepoch-core-spec`

There are other attributes defined in link:./default.nix[`default.nix`].

== Licensing

You are free to copy, modify, and distribute the Zerepoch Platform with
under the terms of the Apache 2.0 license. See the link:./LICENSE[LICENSE]
and link:./NOTICE[NOTICE] files for details.
